### PR TITLE
Add process manager base class with tests and example

### PR DESCRIPTION
**Pull request by condron**
Create a process manager base class and an implementation in the tests to demonstrate it's use.
With a clear process manager defined rename `CorrelatedEDSM` back to `AgregateRoot` for clarity

The Process Manager extends `AggregateRoot` it implements an abstract `IHandle<IMessage>` to indicate that it is designed to respond to external events rather than the method based approach for an aggregate. It also provides a `RecordInput` method that wraps and raises input events for audit. The `InputMsg` class has an explicit null action registered to clarify that input events should not be applied.

n.b.: The example in the tests will demonstrate raising internal state change events that are applied.

### CODE REVIEW

**Comment by tcolemanld** [comment]
I bumped on ProcessManager deriving from AggregateRoot - I think it's ok in the Liskov sense but might still cause some confusion. Instead suggest deriving both AggregateRoot and ProcessManager from CESDM (even though there is no functionality to add to AggergateRoot at the moment, but future functionality could go there if necessary without affecting ProcessManager)

**Comment by tcolemanld** [comment]
Also does a process manager necessarily Handle the messages directly instead of having methods?

**Comment by tcolemanld** [comment]
I think I’ve changed my mind about the aggregate thing. Perhaps we should just say we mean aggregate in the blue book sense and then it’s fine for a process manager to be an aggregate

**Comment by condron** [comment]
@tcolemanld what _other_ senses than the blue book could be interpreted?

**Comment by tcolemanld** [comment]
Both James’s have said before that aggregates receive commands (only) and emit events (only). I’m not sure where that definition comes from though

**Comment by joshkempner** [comment]
Looks good so far.

**Pull request merged**
